// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SecondaryDisks SecondaryDisks
//
// swagger:model SecondaryDisks
type SecondaryDisks struct {

	// size
	Size *ConfigVarString `json:"size,omitempty"`

	// storage class name
	StorageClassName *ConfigVarString `json:"storageClassName,omitempty"`
}

// Validate validates this secondary disks
func (m *SecondaryDisks) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSize(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStorageClassName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SecondaryDisks) validateSize(formats strfmt.Registry) error {
	if swag.IsZero(m.Size) { // not required
		return nil
	}

	if m.Size != nil {
		if err := m.Size.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("size")
			}
			return err
		}
	}

	return nil
}

func (m *SecondaryDisks) validateStorageClassName(formats strfmt.Registry) error {
	if swag.IsZero(m.StorageClassName) { // not required
		return nil
	}

	if m.StorageClassName != nil {
		if err := m.StorageClassName.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("storageClassName")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this secondary disks based on the context it is used
func (m *SecondaryDisks) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSize(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStorageClassName(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SecondaryDisks) contextValidateSize(ctx context.Context, formats strfmt.Registry) error {

	if m.Size != nil {
		if err := m.Size.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("size")
			}
			return err
		}
	}

	return nil
}

func (m *SecondaryDisks) contextValidateStorageClassName(ctx context.Context, formats strfmt.Registry) error {

	if m.StorageClassName != nil {
		if err := m.StorageClassName.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("storageClassName")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SecondaryDisks) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SecondaryDisks) UnmarshalBinary(b []byte) error {
	var res SecondaryDisks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
